"""
Django settings for hids_web project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=-xz!a^$8w7r1vb%gns8lplj@-=5v_g(!mgkf%y#z6s5dt0^&!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True





#esto se modifica para poder acceder a la web, dependiendo de la ip que estas usando
ALLOWED_HOSTS = ['192.168.0.101', '192.168.200.7', '192.168.6.139', '192.168.60.44', '192.168.100.40', 'localhost', '127.0.0.1']






# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hids_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hids_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

#en-us (esto es ingles)

# para que django use hora local de PY, no la UTC (lo de UTC estaba por defecto, (adelantado 2 horas))
TIME_ZONE = 'America/Asuncion'

#TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'










#confuguramos para poder hacer login antes de acceder al 'dashboard' o a las opciones para detecctar intrusos 

# Redirigir después de iniciar sesión exitosamente
LOGIN_REDIRECT_URL = '/dashboard/'

# Redirigir después de cerrar sesión
LOGOUT_REDIRECT_URL = '/login/'












#configuracion para que se pueda recibir en el correo las alertas

# para enviar correos desde Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  #para el envo de correos usando servidor SMTP
EMAIL_HOST = 'smtp.gmail.com'  # protocolo para enviar el correo
EMAIL_PORT = 587  # puerto estandar
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'acostaveron7@gmail.com'      # ⚠️ el correo que va a recibir
EMAIL_HOST_PASSWORD = 'fuqhlslowrldlywr'    # ⚠️ contraseña de app,(generada por seguridad)

# esto indica que el mismo correo es usado para enviar las alertas (mismo correo para enviar y tambien recibir alertas)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# esto es para centralizar el correo, y no modificar en cada scripts, entonces, en cada modulo/scripts solo se usa 'settings.ALERTA_EMAIL_RECEPTOR'
ALERTA_EMAIL_RECEPTOR = 'acostaveron7@gmail.com'

